openapi: 3.0.3
info:
  title:  商品API
  description: 商品API　openapi
  version: 1.0.0
servers:
  - url: https://example.com/api/v0
    description: 本番 API
  - url: http://{host}:{port}/api/v0
    description: 開発用
    variables:
      host:
        default: localhost
      port:
        default: '3000'
paths:
  /products:
    get:
      operationId: openapitutorial.controller.health.call
      summary: サーバーの状態を返します
      description: 商品一覧を30件ずつ取得
      responses:
        '200':
          description: サーバーは正常に動作しています
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_health_response'
components:
  schemas:
    get_health_response:
      description: サーバーの状態のレスポンス
      type: object
      properties:
        status:
          type: string
          enum:
            - ok
      required:
        - status